title: Swati Sharma
profile_img: /assets/img/IMG_9255.jpg
icon_img: /assets/img/icon.webp

name: "Swati Sharma"
job: "Economist"
about_me: "Greetings!<br>I'm a Macroeconomist in the Department of Economics & Finance at the Cameron School of Business at UNCW. My research interests span monetary policy, open economy macroeconomics, and international economics. Fueled by curiosity and good coffee, I'm equally invested in the art of teaching. Join me on this intellectual journey as we delve into the dynamic interplay between economic policies and global markets."

phone_number: 786-683-8620
address: North Carolina, USA
email: swatis0110@gmail.com
linkedin_username: swati-sharma
#github_username: github
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
