title: Swati Sharma
profile_img: /assets/img/IMG_9255.jpg
icon_img: /assets/img/icon.webp

name: "Swati Sharma"
job: "Economist"
#job: "Greetings!"
about_me: "I'm a Macroeconomist in the Department of Economics & Finance at the Cameron School of Business at UNCW. My research interests span monetary policy, open economy macroeconomics, and international economics. Fueled by curiosity and good coffee, I'm equally invested in the art of teaching. Join me on this intellectual journey as we delve into the dynamic interplay between economic policies and global markets."
about_me: "Originally from India, I moved to the U.S. in 2019 to get my doctoral degree. Armed with a bachelor's degree in Economics and two additional master's degrees in the same field, I am fervently engaged in studying the dynamic setup of open economy macroeconomic policies. Alongside my research pursuits, teaching is a genuine passion of mine, and I have gained valuable experience instructing undergraduate courses throughout my doctoral program. An avid reader, I find equal joy in exploring new destinations and expressing my creativity through sketching. I'm always open to new experiences, cultures, and ways of thinking."

phone_number: 000-345-6789
address: City, Country
#github_username: github
#instagram_username: instagram
email: swatis0110@gmail.com
linkedin_username: swati-sharma-b7140a12a
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
