title: Swati Sharma
profile_img: /assets/img/IMG_9255.jpg
icon_img: /assets/img/icon.webp

name: "Swati Sharma"
job: "Economist"
about_me: "Greetings!<br>I am an Economist specializing in monetary policy, open economy macroeconomics, and international economics. My work is driven by a passion for analyzing complex economic systems and uncovering insights that can inform policy decisions and enhance economic outcomes. With strong research skills and a keen ability to synthesize data, I focus on identifying key trends and implications for policymaking and broader global governance. In addition to my research, I am deeply committed to teaching and empowering students. I am committed to fostering a collaborative learning environment where ideas are exchanged freely, critical thinking is encouraged, and economic theory is brought to life. I find great fulfillment in guiding students on their academic journeys and helping them engage with real-world economic challenges while nurturing the next generation of thinkers and problem-solvers."

phone_number: 012-345-6789
address: Miami, USA
email: swatis0110@gmail.com
linkedin_username: swati-sharma0110
#github_username: github
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
